name:                kanji
version:             0.1.0.0
github:              "ptixed/kanji"
license:             BSD3
author:              "Pawel Krogulec"
copyright:           "2019 Pawel Krogulec"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/ptixed/kanji#readme>

dependencies:
- base >= 4.7 && < 5
- text
- vector
- lens
- brick
- vty
- imagemagick
- resourcet
  
library:
    source-dirs: src

executables:
  kanji-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kanji

